# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag
image: java:8
pipelines:
  default:
    - step:
        caches:
          - gradle
        script:         
          - echo "running cucumber tests"
          - bash ./gradlew test
          